# Generated by Django 2.2.1 on 2019-07-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='average_score',
            field=models.FloatField(default=0, verbose_name='平均スコア'),
        ),
    ]
