# Generated by Django 2.2.1 on 2019-08-03 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cacao',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='カカオ含有率'),
        ),
    ]
