# Generated by Django 2.2.1 on 2019-08-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_cacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='liked_by',
        ),
        migrations.AddField(
            model_name='post',
            name='gained_like',
            field=models.PositiveIntegerField(default=0, verbose_name='獲得したLike数'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
