# Generated by Django 2.2.1 on 2019-10-29 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel1_title', models.CharField(max_length=36, verbose_name='トップページのカルーセル１タイトル')),
                ('carousel1_text', models.TextField(blank=True, verbose_name='トップページのカルーセル１テキスト')),
                ('carousel2_title', models.CharField(max_length=36, verbose_name='トップページのカルーセル２タイトル')),
                ('carousel2_text', models.TextField(blank=True, verbose_name='トップページのカルーセル２テキスト')),
                ('carousel3_title', models.CharField(max_length=36, verbose_name='トップページのカルーセル３タイトル')),
                ('carousel3_text', models.TextField(blank=True, verbose_name='トップページのカルーセル３テキスト')),
                ('about', models.TextField(blank=True, verbose_name='aboutページでこのサイトについての説明')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='Site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Webサイトのタイトル', max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(default='Webサイトの説明', max_length=255, verbose_name='サイトの説明')),
                ('keywords', models.CharField(default='Webサイトのキーワード', max_length=255, verbose_name='サイトのSEOキーワード')),
                ('author', models.CharField(default='CHOCO.FAN管理者', max_length=255, verbose_name='管理者')),
                ('email', models.EmailField(default='your_mail@gmail.com', max_length=255, verbose_name='管理者アドレス')),
                ('homepage_url', models.URLField(blank=True, verbose_name='公式サイト')),
                ('insta_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('facebook', models.URLField(blank=True, verbose_name='FaceBook URL')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='Site')),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='aboutページでこのサイトについての説明')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='Site')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_ad_side1', models.TextField(blank=True, verbose_name='アドセンスHTML サイドバー用1')),
                ('google_ad_side2', models.TextField(blank=True, verbose_name='アドセンスHTML サイドバー用2')),
                ('google_ad_main1', models.TextField(blank=True, verbose_name='アドセンスHTML メイン（col-9）用1')),
                ('google_ad_main2', models.TextField(blank=True, verbose_name='アドセンスHTML メイン（col-9）用2')),
                ('rakuten_ad_side1', models.TextField(blank=True, verbose_name='楽天アフィリエイト サイドバー用1')),
                ('rakuten_ad_side2', models.TextField(blank=True, verbose_name='楽天アフィリエイト サイドバー用2')),
                ('a8_ad_side1', models.TextField(blank=True, verbose_name='A8ネット サイドバー用2')),
                ('amazon_ad_side1', models.TextField(blank=True, verbose_name='Amazon サイドバー用2')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='Site')),
            ],
        ),
    ]
