# Generated by Django 2.2.1 on 2019-10-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='a8_ad_side2',
            field=models.TextField(blank=True, verbose_name='A8ネット サイドバー用2'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='amazon_ad_side2',
            field=models.TextField(blank=True, verbose_name='Amazon サイドバー用2'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='a8_ad_side1',
            field=models.TextField(blank=True, verbose_name='A8ネット サイドバー用1'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='amazon_ad_side1',
            field=models.TextField(blank=True, verbose_name='Amazon サイドバー用1'),
        ),
    ]
