# Generated by Django 2.2.2 on 2020-03-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0003_imagesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topsetting',
            name='about',
        ),
    ]
