# Generated by Django 2.2.1 on 2019-07-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190710_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_bloger',
        ),
        migrations.AddField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False, verbose_name='コラム執筆可'),
        ),
    ]
