# Generated by Django 2.2.1 on 2019-07-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190720_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.TextField(blank=True, verbose_name='プロフィール'),
        ),
    ]
