# Generated by Django 2.2.1 on 2019-08-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190803_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_writer',
            new_name='is_columnist',
        ),
    ]
