# Generated by Django 2.2.1 on 2019-10-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190805_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='ニックネーム'),
        ),
    ]
