# Generated by Django 2.2.1 on 2019-09-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_likeshop_reviewshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_fb',
            field=models.URLField(blank=True, verbose_name='Facebook（店舗アカウント）'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_insta',
            field=models.URLField(blank=True, verbose_name='Instagram（店舗アカウント）'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_tw',
            field=models.URLField(blank=True, verbose_name='Twitter（店舗アカウント）'),
        ),
        migrations.AddField(
            model_name='shop',
            name='short_content',
            field=models.TextField(default=1, verbose_name='店舗紹介文'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='content',
            field=models.CharField(max_length=100, verbose_name='店舗概要'),
        ),
    ]
