# Generated by Django 2.2.1 on 2019-09-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190927_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='content',
            field=models.TextField(verbose_name='店舗紹介文'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='short_content',
            field=models.CharField(max_length=100, verbose_name='店舗概要'),
        ),
    ]
