# Generated by Django 2.2.1 on 2019-10-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190927_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='url',
            new_name='shop_url',
        ),
    ]
