# Generated by Django 2.2.1 on 2019-10-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191009_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_url',
            field=models.URLField(blank=True, default=111, verbose_name='店舗URL'),
            preserve_default=False,
        ),
    ]
