# Generated by Django 2.2.1 on 2019-11-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shop_off_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='hirata_date',
            field=models.DateField(blank=True, default='2001-01-01', verbose_name='Hirata103導入日'),
        ),
        migrations.AddField(
            model_name='shop',
            name='hirata_flag',
            field=models.BooleanField(default=False, verbose_name='hirada103導入かどうか'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='店舗メール'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_tel',
            field=models.CharField(blank=True, max_length=12, verbose_name='店舗電話番号'),
        ),
    ]
