# Generated by Django 2.2.1 on 2019-11-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20191108_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='店舗名'),
        ),
    ]
