# Generated by Django 2.2.1 on 2019-12-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='tag',
            field=models.ManyToManyField(blank=True, to='shop.Tag'),
        ),
    ]
