# Generated by Django 2.2.1 on 2020-02-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_shop_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewshop',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], verbose_name='レビュースコア'),
        ),
    ]
