# Generated by Django 2.2.1 on 2020-09-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200216_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_line',
            field=models.CharField(blank=True, max_length=100, verbose_name='Line公式'),
        ),
    ]
