# Generated by Django 2.2.1 on 2019-08-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='public_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
