# Generated by Django 2.2.1 on 2019-08-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_news_public_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_date',
            field=models.DateTimeField(),
        ),
    ]
