# Generated by Django 2.2.1 on 2019-10-01 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_pagesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesetting',
            name='footer_text',
        ),
    ]
