# Generated by Django 2.2.1 on 2019-07-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='image/column/'),
        ),
    ]
