# Generated by Django 2.2.1 on 2019-07-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0002_column_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='content',
            field=models.CharField(max_length=1200, verbose_name='コンテンツ'),
        ),
    ]
