# Generated by Django 2.2.1 on 2019-08-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0004_auto_20190802_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='writer',
            new_name='author',
        ),
    ]
