# Generated by Django 2.2.1 on 2019-10-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0005_auto_20190804_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='content_script',
            field=models.TextField(blank=True, verbose_name='スクリプト'),
        ),
        migrations.AlterField(
            model_name='column',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='アクセス数（累積）'),
        ),
    ]
