# Generated by Django 2.2.1 on 2020-02-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0006_auto_20191004_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_index',
            field=models.BooleanField(default=True, help_text='H2タグが自動的に目次として認識されます', verbose_name='目次有無'),
        ),
    ]
