# Generated by Django 2.2.1 on 2020-02-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0007_column_is_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='下書きの場合はチェックを入れてください。公開されません。', verbose_name='下書きの場合はチェック'),
        ),
    ]
