# Generated by Django 4.2.3 on 2023-07-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0008_column_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
